config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users
  get '' => 'articles#index'
  resources :articles, :except => :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #Todo: before_action

  def index
    @articles = Article.includes(:user).order(id: "DESC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>
  <!--  todo: validation_error_message  -->
  <div class="md-form">
    <label>タイトル</label>
    <%= f.text_field :title, required: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <label></label>
    <%= f.text_area :body, required: true, class: "form-control", rows: "16", placeholder: "本文" %>
  </div>
  <%= f.button "投稿する", class: "btn blue-gradient btn-block" %>
<% end %>

app/views/articles/index.html.erb
<%= render :partial => 'shared/nav' %>

<div class="container">
  <% @articles.each do |article| %>
  <div class="card mt-3">
    <div class="card-body d-flex flex-row">
      <i class="fas fa-user-circle fa-3x mr-1"></i>
      <div>
        <div class="font-weight-bold">
          <%= article.user.name %>
        </div>
        <div class="font-weight-lighter">
          <%= l article.created_at %>
        </div>
      </div>
    </div>
    <div class="card-body pt-0 pb-2">
      <h3 class="h4 card-title">
        <%= article.title %>
      </h3>
      <div class="card-text">
        <%= article.body %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render :partial => 'shared/nav' %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card mt-3">
        <div class="card-body pt-0">
          <div class="card-text">
            <%= render :partial => 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.11/css/mdb.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.11/js/mdb.min.js"></script>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand navbar-dark blue-gradient">

  <a class="navbar-brand" href="/"><i class="far fa-sticky-note mr-1"></i>memo</a>

  <ul class="navbar-nav ml-auto">

    <% unless user_signed_in? %>
    <li class="nav-item">
      <%= link_to "ユーザー登録", new_user_registration_path(), class: "nav-link" %>
    </li>
    <% end %>

    <% unless user_signed_in? %>
    <li class="nav-item">
      <%= link_to "ログイン", new_user_session_path(), class: "nav-link" %>
    </li>
    <% end %>

    <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to(new_article_path, class: "nav-link") do %>
        <i class="fas fa-pen mr-1"></i>投稿する
      <% end %>
    </li>
    <% end %>

    <% if user_signed_in? %>
    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </li>
    <!-- Dropdown -->
    <% end %>

  </ul>

</nav>